---
# tasks file for postfix

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install postfix
  package:
    name: "{{ postfix_packages }}"
    state: present

- name: create group
  group:
    name: "{{ postfix_group }}"
    state: present

- name: configure postfix (main.cf)
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    validate: postconf -d -c %s
    mode: "0644"
  notify:
    - restart postfix

- name: configure postfix (master.cf)
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    validate: postconf -d -c %s
    mode: "0644"
  notify:
    - restart postfix

- name: force all notified handlers to run
  meta: flush_handlers

- name: configure aliases
  lineinfile:
    path: "{{ postfix_alias_path }}"
    regexp: "^{{ item.name }}:"
    line: "{{ item.name }}: {{ item.destination }}"
    mode: "0644"
  when:
    - postfix_aliases is defined
  loop: "{{ postfix_aliases }}"
  notify:
    - rebuild alias database
    - restart postfix
  loop_control:
    label: "{{ item.name }}"

- name: configure sender_access
  lineinfile:
    path: "{{ postfix_sender_access_path }}"
    regexp: "^{{ item.domain }}"
    line: "{{ item.domain }} {{ item.action }}"
    create: yes
    mode: "0644"
  when:
    - postfix_sender_access is defined
  loop: "{{ postfix_sender_access }}"
  notify:
    - rebuild sender_access database
    - restart postfix
  loop_control:
    label: "{{ item.domain }}"

- name: configure recipient_access
  lineinfile:
    path: "{{ postfix_recipient_access_path }}"
    regexp: "^{{ item.domain }}"
    line: "{{ item.domain }} {{ item.action }}"
    create: yes
    mode: "0644"
  when:
    - postfix_recipient_access is defined
  loop: "{{ postfix_recipient_access }}"
  notify:
    - rebuild recipient_access database
    - restart postfix
  loop_control:
    label: "{{ item.domain }}"

- name: force all notified handlers to run
  meta: flush_handlers

- name: start and enable postfix
  service:
    name: "{{ postfix_service }}"
    state: started
    enabled: yes

- name: flush handlers
  meta: flush_handlers
